### ISSUE TITLE
HpsException: mac check in GCM failed

### ISSUE THREAD

**Issue by ddelizia** [hps/heartland-java#3]
I'm trying to decrypt the apple pay paymentToken. I'm doing as for the README.md:

```
PaymentToken token = new PaymentToken(new String(Files.readAllBytes(Paths.get("/pathToMyJson/file.json"))));
DecryptService service = new DecryptService("/PathToApplePayP12File/ApplePayCertKey.p12", "p12Password");
PaymentData paymentData = service.decrypt(token);
```

But I'm getting the following error:

```
com.hps.integrator.infrastructure.HpsException: mac check in GCM failed

    at com.hps.integrator.applepay.ecv1.DecryptService.decrypt(DecryptService.java:142)
    at com.hps.integrator.tests.DaniloTest.test(DaniloTest.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: javax.crypto.AEADBadTagException: mac check in GCM failed
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.doFinal(Unknown Source)
    at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
    at javax.crypto.Cipher.doFinal(Cipher.java:2165)
    at com.hps.integrator.applepay.ecv1.DecryptService.decrypt(DecryptService.java:132)
    ... 27 more
```

Any help

**Comment by securesubmit-buildmaster** [comment]
This is something that is caused by bad input. I would check the contents of the file.json to ensure they’re complete.

Thanks,

[colorline]

Russell Everett
Senior Developer
Payment Processing, Payroll Solutions and Rewards
P: (812) 280-8222 x65622
One Heartland Way
Jeffersonville, IN 47130
HeartlandPaymentSystems.comhttp://www.heartlandpaymentsystems.com/   facebook.comhttp://www.facebook.com/HeartlandHPY/
[Heartland Payment Systems]http://www.heartlandpaymentsystems.com/
CONFIDENTIALITY WARNING: This email may contain privileged or confidential information and is for the
sole use of the intended recipient(s). Any unauthorized use or disclosure of this communication is prohibited.
If you believe that you have received this email in error, please notify the sender immediately and delete it from
your system.

**Comment by cmmouritsen** [comment]
I'm getting this same error after updating my Apple-Pay certificate. It was working before, my certificate is expiring today, so I updated the certificate and revoked the old certificate and now I'm getting this error. Any suggestions?

**Comment by cmmouritsen** [comment]
FWIW, it seems I just didn't wait long enough for the new certificate to be activated. This error eventually went away, but it took hours.
